"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
format = "$directory$git_branch$git_status$character"

[directory]
truncation_length = 2
truncate_to_repo = true
style = "blue"

[git_branch]
format = " [$branch]($style)"
style = "purple"

[git_status]
style = "yellow"

[character]
success_symbol = "[›](green)"
error_symbol = "[›](red)"