"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 1000

format = """
[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$nodejs\
$python\
$golang\
$rust\
$kubernetes\
[](fg:#86BBD8 bg:#06969A)\
$time\
[ ](fg:#06969A)\
$character
"""

[username]
show_always = true
style_user = "bg:#9A348E fg:#ffffff bold"
style_root = "bg:#9A348E fg:#ffffff bold"
format = "[ $user ]($style)"
disabled = false

[directory]
style = "bg:#DA627D fg:#ffffff bold"
format = "[ $path ]($style)"
truncation_length = 3
truncate_to_repo = true
home_symbol = "~"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Code" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:#FCA17D fg:#1C1C1C bold"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#FCA17D fg:#1C1C1C bold"
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = ""
style = "bg:#86BBD8 fg:#1C1C1C bold"
format = "[ $symbol $version ]($style)"
detect_files = ["package.json", ".node-version"]
detect_extensions = ["js", "mjs", "cjs", "ts"]

[python]
symbol = ""
style = "bg:#86BBD8 fg:#1C1C1C bold"
format = "[ $symbol $version ]($style)"

[golang]
symbol = ""
style = "bg:#86BBD8 fg:#1C1C1C bold"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "bg:#86BBD8 fg:#1C1C1C bold"
format = "[ $symbol $version ]($style)"

[kubernetes]
symbol = "☸"
style = "bg:#86BBD8 fg:#1C1C1C bold"
format = "[ $symbol $context( $namespace) ]($style)"
disabled = false

[time]
disabled = false
time_format = "%H:%M"
style = "bg:#06969A fg:#ffffff bold"
format = "[ ♥ $time ]($style)"

[character]
success_symbol = "[❯](bold #86BBD8)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"